-- Script to create the schema of the SQLite-DB 'test'
DROP TABLE Food;
CREATE TABLE Food (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Name VARCHAR NOT NULL
);

DROP TABLE Favorites;
CREATE TABLE Favorites (
	ID INTEGER PRIMARY KEY REFERENCES Food
);

DROP TABLE Plan;
CREATE TABLE Plan (
	Day DATE PRIMARY KEY,
	Food INTEGER REFERENCES Food 
);
